### ISSUE TITLE
Change attribute privateUsageAdmissable

### ISSUE THREAD

**Issue by montanajava** [blw-ofag-ufag/eCH-0263#14]
In element plantProtectionProductTypeTyp.privateUsageAdmissable 

privateUsageAdmissable should be called admissableUsage 
 
PRIVATE Privat  plus FR und IT
PROFESSIONAL Professionell  plus FR und IT   (default) 

Kardinalität should be 1 - 2 to allow the indication of both of them.

**Comment by anjaaeschlimann** [comment]
Korrekt, Abstimmung Ryan mit Andrea hat ergeben, dass Produkte entweder Privat, Professionell oder Beides sein können
