### ISSUE TITLE
facilitySpecific should be renamed to allowedForFacilitySpecific

### ISSUE THREAD

**Issue by montanajava** [blw-ofag-ufag/eCH-0263#19]
The attribute name facilitySpecific does not do justice to what this attribute is intended to accomplish.

The practice in the HofRec world is that a metaIngredient (the template upon which a product is ultimately defined) has an _intended_ use, i.e. it is defined up-front whether a farmer can deviate from the template as defined by BLW staff. To accomplish this today in Hoduflu, the attribute  allows TRUE | FALSE | BOTH.   BOTH means that a metaIngredient can be used for standard products and also for bespoke products defined by a farmer.

BOTH is of course nonsensical but necessary _if_ we in turn have an attribute name that does not represent the actual domain requirements.

As such, to solve the problem, it is recommended that attribute facilitySpecific be called allowedForFacilitySpecific. Doing so allows for a sensible use of TRUE | FALSE as is recommended in https://github.com/blw-ofag-ufag/eCH-0263/issues/18.

**Comment by anjaaeschlimann** [comment]
ok
