### ISSUE TITLE
Add Constraints (Auflagen) to PlantProtectionProduct

### ISSUE THREAD

**Issue by montanajava** [blw-ofag-ufag/eCH-0263#3]
Usage constraints or restrictions are very valuable to know when, for instance, applying phytosanitary or plant protection product on a field. Such constraints, are, however, fully free text and are not parseable.

Constraints, or Restrictions (de=Auflage) should be machine-parsable and added as a 0-n attribute to a plant protection product.

The description of how that looks should flow from infoPhyto.

**Comment by montanajava** [comment]
Auflagen come from infoPhyto and are currently described in freetext format. These should be parseable. 

Examples: Can not be used within 10 metres from water.

**Comment by AFoletti** [comment]
This will be solved at the PSM level (works ongoing) and is not something to be handled by this standard
