### ISSUE TITLE
feedstuffType:referenceToProduct correct?

### ISSUE THREAD

**Issue by montanajava** [blw-ofag-ufag/eCH-0263#30]
Is it correct, that feedStuffType references a product from which it is derived?

Is it true that we have "meta" definitions for Feedstuff?

It is likely correct as I am seeing later a reference to metaNutrient, which seems to indicate that this is correct.

A simple verification from Anja or Ryan is requested.

**Comment by lars-steffen** [comment]
its ok - the reference is used for facility specific products.
