### ISSUE TITLE
Products should have relationship to ProductFamily

### ISSUE THREAD

**Issue by montanajava** [blw-ofag-ufag/eCH-0263#42]
In working group discussions it was decided that there should be no relationship of a respective product to the ProductFamily enumeration.  The reason for that was because it was in once sense redundant: the name of the class of the product revealed the family. 

That said, "software" has no way of knowing that -- without some form of intelligence.

This proposal is to add that relationship for all products (ManureRecycing, PlantProtection, and so on).

**Comment by AFoletti** [comment]
@montanajava could you please better specify what you meant (with an example if possible). Otherwise, this will be closed as "won't fix"

**Comment by montanajava** [comment]
The rationale for the change request is so that systems can explicitly, not implicitly, know to what productFamily a product belongs. This allows for filtering. Use cases include UIs allowing users to filter products by family, and systems that want to filter out certain families of products from consideration in any number of contexts. A branch https://github.com/blw-ofag-ufag/eCH-0263/tree/42-referenceProductFamily has been created as an example of how it could be implemented.

**Comment by montanajava** [comment]
Agreed. This issue was created under a false premise of lists of products of multiple families being unified into one list. At least in the case of one well-known active BLW project, that has turned out to be not the case. In that project within the GUI, products of divergent families are, in fact, separated into separate tabs. I withdraw this proposal and support your position of closing this with "won't fix". Sorry for the run-around.

As to your second paragraph, I would recommend a new issue for that.

**Comment by AFoletti** [comment]
All right! Thanks for the discussion. Even if we go in another direction, you raised an important issue.

I will close this one and delete your branch.
As you suggested, there is a new ticket up for discussion: #61
