### ISSUE TITLE
IngredientType_Delete

### ISSUE THREAD

**Issue by anjaaeschlimann** [blw-ofag-ufag/eCH-0263#46]
Aus Diskussion 05.02.2024

Vorschlag IngredientType überall "embedded" verwenden statt über IngredientType
So könnte man auch auf Attribute ID und Descriptor verzichten (Keine Redundanz zu Produkt)

--> ASAP zu klären und wenn, dann als kleine Änderung noch an Expertengruppe melden

**Comment by montanajava** [comment]
Ob im Product embedded oder nicht-embedded, das definierte Element IngredientTyp behält seine Daseinsberechtigung. Die anderen Attribute dienen zur vollständigen multilingualen Beschreibung und Verwendungseingrenzung. 

Bedenke bitte: Ingredient ist ein "Catch-All"-Begriff für Inhaltsstoff, Wirkstoff, Nährstoff. Diese "leben" unabhängig von einem Produkt. 

Wenn jedoch doch eingebettet werden soll, dann soll in der Tat das ID als Attribut von der Typdefinierung entfernt werden.  Dies hätte zur Folge: Ein Ingredient kann ohne ID nicht über Produkte hinweg nicht verwendet werden. Von der der architektonischen Idee, dass ein Ingredient eine eigenständige Entität sei, müsste Abschied genommen werden, und dies für alle Produktfamilien.

Finally: Wenn eine Schnittstelle einen Ingredienten einbetten soll, ist nicht vom Standard verboten.

Meine Empfehlung: keine Veränderung. Schnittstellen sind nicht behindert. Das Existieren eines Ingredienten als Entität bleibht  ermöglicht, was nach meinem Verständnis der Realität entspricht.

**Comment by lars-steffen** [comment]
Decision on 2024-02-07: ingredient will be embedded, but it should have its own id/descriptor with cardinality 0-1
